version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "orderConfirmDB"
      POSTGRES_USER: "ps"
      POSTGRES_PASSWORD: "ps"
    ports:
      - "5436:5432"