#version: '3.1'
#services:
#  oracle-db:
#    image: container-registry.oracle.com/database/enterprise:latest
#    environment:
#      - ORACLE_SID=orderDB
#      - ORACLE_PDB=oracle
#      - ORACLE_PWD=oracle
#    ports:
#      - 1521:1521
#    volumes:
#      - oracle-data:/opt/oracle/oradata
#      - oracle-backup:/opt/oracle/backup
#    healthcheck:
#      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

#volumes:
#  oracle-data:
#  oracle-backup:

version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "orderDB"
      POSTGRES_USER: "ps"
      POSTGRES_PASSWORD: "ps"
    ports:
      - "5433:5432"